./output/generateIntData.out: ./int.c
	gcc ./int.c -lm -o ./output/generateIntData.out
	./output/generateIntData.out

./output/generateLongData.out: ./long.c
	gcc ./long.c -lm -o ./output/generateLongData.out
	./output/generateLongData.out

clean:
	rm ./data/int/*
	rm ./data/long/*
	rm ./output/*
