./*.class: ./*.java
	javac Bubble.java BubbleRec.java Cocktail.java Comb.java Cycle.java Heap.java Gnome.java Insertion.java Merge.java MergeBu.java Quick.java Radix.java Selection.java Shell.java SortBasedOnFile.java

clean:
	rm -f *.class
