./*.class: ./*.java
	javac Bogo.java Bubble.java BubbleRec.java Cocktail.java Comb.java Cycle.java Heap.java Gnome.java Insertion.java InsertionRec.java Merge.java MergeBu.java Pancake.java Quick.java Radix.java Selection.java Shell.java SortBasedOnFile.java

clean:
	rm -f *.class
