./*.class: ./*.java
	javac -Xlint:unchecked Bubble.java BubbleRec.java Cocktail.java Heap.java Insertion.java Merge.java MergeBu.java Quick.java Selection.java Shell.java SortBasedOnFile.java

clean:
	rm -f *.class
