*.out: *.c *.h
	gcc sort_based_on_file.c bead.c bead.h bubble.c bubble.h bogo.c bogo.h bucket.c bucket.h cocktail.h cocktail.c comb.c comb.h counting.c counting.h cycle.c cycle.h gnome.h gnome.c heap.h heap.c insertion.c insertion.h merge.h merge.c pancake.c pancake.h quick.h quick.c radix.c radix.h selection.h selection.c shaker.h shaker.c shell.h shell.c stooge.h stooge.c -lm -o sort_based_on_file.out

clean:
	rm -f *.out
