*.out: *.c *.h
	gcc sort_based_on_file.c heap.c heap.h bubble.c bubble.h bogo.c bogo.h bucket.c bucket.h comb.c comb.h counting.c counting.h cycle.c cycle.h insertion.c insertion.h merge.h merge.c pancake.c pancake.h quick.h quick.c radix.c radix.h selection.h selection.c shaker.h shaker.c shell.h shell.c -lm -o sort_based_on_file.out

clean:
	rm -f *.out
